---
title: "p8106_midterm_project"
author: "David DeStephano"
date: "March 27, 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Load the data set
Tips for dealing with large data https://rpubs.com/msundar/large_data_analysis 

```{r message=FALSE}
library(tidyverse)
library(summarytools)
library(cowplot)
sparcs<-read_csv("Hospital_Inpatient_Discharges__SPARCS_De-Identified___2013.csv")

sparcs %>% janitor::clean_names() %>%  ggplot(aes(x = age_group, y=total_charges, fill = age_group))+
  geom_boxplot() +ylim(0,50000)

```



##2,000,000 rows is excessive, so just going to look at newborns and see if we can predict costs
```{r}
<<<<<<< HEAD
newborns<-sparcs %>% filter(`Birth Weight`!="0000") %>% janitor::clean_names()
```

##Descriptive Stats
```{r warning=FALSE}
dfSummary(newborns) 

newborns %>% ggplot(aes(x=total_costs))+
  geom_histogram()+xlim(0,50000)

newborns %>% ggplot(aes(x=total_charges))+
  geom_histogram()+xlim(0,50000)


ggplot(newborns, aes(x = total_charges, y = ..density..)) + 
    stat_density(geom="line")  +xlim(0,50000)


newborns %>% ggplot(aes(x = race, y=total_charges, fill = race))+
  geom_boxplot() +ylim(0,50000)

```



```{r}



  
```



=======
#dfSummary(sparcs) 
```


test test  test
>>>>>>> 3a1e7b6198488556daff74a8f4fb45a9547766a1


